server.port=8085
spring.application.name=payment-service

resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3

management.endpoints.web.exposure.include=*
